name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore src/MonacoEditor.WinUI3/MonacoEditor.WinUI3.csproj

    - name: Build
      run: dotnet build src/MonacoEditor.WinUI3/MonacoEditor.WinUI3.csproj -c Release --no-restore
