name: Test

on:
  push:
    branches: [ main ]
    paths:
    - 'src/MonacoEditor.WinUI3/**'
    - 'src/MonacoEditor.WinUI3.Tests/**'
    - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/MonacoEditor.WinUI3/**'
    - 'src/MonacoEditor.WinUI3.Tests/**'
    - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore src/MonacoEditor.WinUI3.Tests/MonacoEditor.WinUI3.Tests.csproj

    - name: Test
      run: dotnet test src/MonacoEditor.WinUI3.Tests/MonacoEditor.WinUI3.Tests.csproj -c Release --no-restore --logger "trx;LogFileName=results.trx"

    - name: Publish test results
      uses: dorny/test-reporter@v3
      if: always()
      with:
        name: MSTest Results
        path: '**/results.trx'
        reporter: dotnet-trx
